delete from role;
delete from pack_member;
delete from pack;
INSERT INTO pack VALUES (1,'admin','admin','admin','admin street','00000000000','admin@admin.com','admin');
INSERT INTO pack VALUES (2,'user','Michael','Choinoski','1234 Willow Street','14142912312','michon@gmail','user');
INSERT INTO pack VALUES (3,'Awesome Pack!','Andrew','Cutler','12 Ganderson Court','16081234567','random@yahoo.com','RedBike21');
INSERT INTO pack VALUES (4,'Number 4',' ',' ',' ',' ',' ','password');
INSERT INTO pack VALUES (5,'random_pack',' ',' ',' ',' ',' ','randompassword');
INSERT INTO pack_member VALUES (1,1,'Odo', 'S','Mixed','M','2016-07-14',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO pack_member VALUES (2,2,'Boomer', 'L','Black Lab','M','2013-08-11',0,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO pack_member VALUES (3,2,'Pow', 'L','Black Lab','M','2014-03-22',0,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO pack_member VALUES (4,3,'Lexi', 'S','Beagle','F','2011-12-18',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO pack_member VALUES (5,3,'Lucy', 'M','Poodle','F','2016-01-03',0,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO pack_member VALUES (6,4,'Dog', 'M','Boxer','M','2007-01-01',1,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO role VALUES (1,CURRENT_TIMESTAMP(),'admin',CURRENT_TIMESTAMP(),'admin',1);
INSERT INTO role VALUES (2,CURRENT_TIMESTAMP(),'user',CURRENT_TIMESTAMP(),'user',2);
INSERT INTO role VALUES (3,CURRENT_TIMESTAMP(),'user',CURRENT_TIMESTAMP(),'Awesome Pack!',3);
INSERT INTO role VALUES (4,CURRENT_TIMESTAMP(),'user',CURRENT_TIMESTAMP(),'Number 4',4);
INSERT INTO role VALUES (5,CURRENT_TIMESTAMP(),'user',CURRENT_TIMESTAMP(),'random_pack',5);